# Generated by Django 5.1.4 on 2025-05-19 09:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('task_management_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='task',
            old_name='endTime',
            new_name='end_time',
        ),
        migrations.RenameField(
            model_name='task',
            old_name='startTime',
            new_name='start_time',
        ),
    ]
