# Generated by Django 5.1.4 on 2025-05-29 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task_management_app', '0003_task_assigned_to'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='category',
            field=models.CharField(choices=[('work', 'Work'), ('personal', 'Personal'), ('urgent', 'Urgent')], default='work', max_length=20),
        ),
        migrations.AddField(
            model_name='task',
            name='status',
            field=models.CharField(choices=[('to_do', 'To Do'), ('in_progress', 'In Progress'), ('done', 'Done')], default='to_do', max_length=20),
        ),
    ]
